### ISSUE TITLE
Mac: error on startup if mouse cursor moving when window created

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/omnivore#101]
On the Mac, if I happen to have the mouse cursor over the window as it's being created, it does:
```python
Traceback (most recent call last):
  File "/Users/rob.mcmullen/src/omnivore/omnivore/utils/wx/bitviewscroller.py", line 438, in on_motion
    self.on_motion_update_status(evt)
  File "/Users/rob.mcmullen/src/omnivore/omnivore/utils/wx/bitviewscroller.py", line 444, in on_motion_update_status
    byte, bit, inside = self.event_coords_to_byte(evt)
  File "/Users/rob.mcmullen/src/omnivore/omnivore/utils/wx/bitviewscroller.py", line 760, in event_coords_to_byte
    zw, zh = self.get_zoom_factors()
  File "/Users/rob.mcmullen/src/omnivore/omnivore/utils/wx/bitviewscroller.py", line 652, in get_zoom_factors
    zw = self.font.scale_w
AttributeError: 'NoneType' object has no attribute 'scale_w'
```

**Comment by robmcmullen** [comment]
Red herring. It was caused by an incomplete initialization due to an ImportError
