### ISSUE TITLE
text recognizer broken

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/omnivore#177]
Loading a text file:
```Traceback (most recent call last):
  File "/noaa/maproom-deps/omnivore/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/noaa/maproom-deps/omnivore/omnivore/framework/application.py", line 216, in _application_initialized_fired
    self.load_file(arg, None, task_id=task_id)
  File "/noaa/maproom-deps/omnivore/omnivore/framework/application.py", line 336, in load_file
    document = self.guess_document(guess)
  File "/noaa/maproom-deps/omnivore/omnivore/framework/application.py", line 315, in guess_document
    document = service.recognize(guess)
  File "/noaa/maproom-deps/omnivore/omnivore/file_type/driver.py", line 38, in recognize
    document = recognizer.load(guess)
AttributeError: 'PlainTextRecognizer' object has no attribute 'load'
```

**Comment by robmcmullen** [comment]
Actually, this is quite high because it's preventing the title screen from loading
