### ISSUE TITLE
map edit load fails when .omnivore file present

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/omnivore#210]
```
Traceback (most recent call last):
  File "/noaa/maproom-deps/omnivore/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/noaa/maproom-deps/omnivore/omnivore/framework/application.py", line 158, in _application_initialized_fired
    self.load_file(arg, None, task_id=task_id)
  File "/noaa/maproom-deps/omnivore/omnivore/framework/application.py", line 297, in load_file
    document = self.guess_document(guess)
  File "/noaa/maproom-deps/omnivore/omnivore/framework/application.py", line 276, in guess_document
    document = service.recognize(guess)
  File "/noaa/maproom-deps/omnivore/omnivore/file_type/driver.py", line 38, in recognize
    document = recognizer.load(guess)
  File "/noaa/maproom-deps/omnivore/omnivore8bit/file_type/atrcopy_parsers.py", line 27, in load
    doc.load_metadata(guess)
  File "/noaa/maproom-deps/omnivore/omnivore/framework/document.py", line 161, in load_metadata
    extra = self.load_extra_metadata(guess)
  File "/noaa/maproom-deps/omnivore/omnivore8bit/document.py", line 59, in load_extra_metadata
    extra = check_builtin(self)
  File "/noaa/maproom-deps/omnivore/omnivore8bit/utils/extra_metadata.py", line 202, in check_builtin
    e = match(doc)
  File "/noaa/maproom-deps/omnivore/omnivore8bit/utils/extra_metadata.py", line 49, in Getaway
    _, s, _ = doc.find_segments_in_range(playfield)[0]
IndexError: list index out of range
```

**Comment by robmcmullen** [comment]
Looks like this happens when the file size changes?

**Comment by robmcmullen** [comment]
OK, this actually only fails when the executable has been mangled
