### ISSUE TITLE
Crash opening "Scavange-original" ATR

### ISSUE THREAD

**Issue by 48kRAM** [robmcmullen/omnivore#262]
#---- System Information ----#
Omnivore XL Version: 1.0rc4
Operating System: Windows 8 (build 9200), 64-bit edition
Python Version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
wxPython Version: 3.0.2.0 msw (classic)
wxPython Info: (__WXMSW__, wxMSW, unicode, wx-assertions-on, SWIG-1.3.29)
Python Encoding: Default=ascii  File=mbcs
wxPython Encoding: cp1252
System Architecture: 32bit AMD64
Byte order: little
Frozen: True
#---- End System Information ----#

#---- Traceback Info ----#
*** Wed Jun 10 17:20:17 2020 ***
Traceback (most recent call last):
  File "pyface\ui\wx\action\action_item.py", line 507, in _on_tool
  File "pyface\tasks\action\task_action_controller.py", line 31, in perform
  File "omnivore\framework\actions.py", line 153, in perform
  File "omnivore\framework\application.py", line 294, in load_file
  File "omnivore\framework\application.py", line 273, in guess_document
  File "omnivore\file_type\driver.py", line 33, in recognize
  File "omnivore8bit\file_type\atrcopy_parsers.py", line 18, in identify
  File "atrcopy\parsers.py", line 163, in iter_parsers
  File "atrcopy\parsers.py", line 143, in guess_parser_for_mime
  File "atrcopy\parsers.py", line 26, in __init__
  File "atrcopy\parsers.py", line 58, in parse
  File "atrcopy\parsers.py", line 68, in get_image
  File "atrcopy\spartados.py", line 116, in __init__
  File "atrcopy\ataridos.py", line 434, in __init__
  File "atrcopy\diskimages.py", line 102, in __init__
  File "atrcopy\diskimages.py", line 142, in setup
  File "atrcopy\diskimages.py", line 147, in get_metadata
  File "atrcopy\spartados.py", line 174, in get_directory
  File "atrcopy\spartados.py", line 27, in __init__
  File "atrcopy\ataridos.py", line 93, in __init__
  File "atrcopy\spartados.py", line 67, in parse_raw_dirent
AttributeError: can't set attribute

#---- End Traceback Info ----#

#---- Notes ----#
Please provide additional information about the crash here:

I tried to open the ATR of Kay's "Scavange" game - as available on his github. This omnivore will open other ATRs, just crashes on this one
https://github.com/savetz/Scavange/blob/master/Scavange-original.atr

**Comment by robmcmullen** [comment]
It seems to detect it as a spartados image? Omnivore 2 has a totally different disk image reader, and thinks it's a Jumpman disk, so that's not correct either!

**Comment by 48kRAM** [comment]
The disk image does use SpartaDOS - I can see that in the emulator. No idea how Kay created this disk image -- if it's a raw image of his actual old floppy or an assembled image built using modern tools.

**Comment by robmcmullen** [comment]
I never implemented SpartaDOS format because I could never find a good enough byte-level description of its format. Crashing is not optimal, however. :) I'll at least need to default to an unsupported binary image.
